# Generated by Django 2.1.8 on 2020-07-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meituan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='remark',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='index',
            name='shop_id',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='index',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
