# Generated by Django 2.1.8 on 2020-07-11 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meituan', '0002_auto_20200711_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='index',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.DO_NOTHING, to='meituan.Index'),
        ),
    ]
