# Generated by Django 2.1.8 on 2020-07-11 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meituan', '0003_shop_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='remark',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='shop_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='ave_price',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='comments',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='hours',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='index',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='meituan.Index'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='shop',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
