# Generated by Django 2.1.8 on 2020-07-11 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meituan', '0005_auto_20200711_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='index',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='meituan.Index'),
        ),
    ]
